### ISSUE TITLE
Make it more obvious that "submit for review" needs to be pressed after entering requirements

### ISSUE THREAD

**Issue by mjpritchard** [cedadev/jasmin-manage-ui#19]

**Comment by mjones07** [comment]
Make the change to the button more obvious, and remind the user that this needs doing somehow - e.g. textbox, pop-up, or something

**Comment by mjones07** [comment]
Add some text under the service tab:
project owner/collaborator: 
consortium manager:
Check the state the project is in to catch when user is both

**Comment by mjones07** [comment]
When viewing the services as a project member and the project is in editable state, have the following text under the services tab: "Please ensure that you click the "Submit for review" button once you have added your requirements to all services."

When view the project as a consortium manager and the project is in under review state, have the following text under the services tab: "Please click either "Request changes" or "Submit for provisioning" once you have made decisions on all the requirements for the project."

**Comment by mjones07** [comment]
Sorted in [5cae2f2](https://github.com/cedadev/jasmin-manage-ui/commit/5cae2f24204aa028eeadb0d151b3b734ce1170b4)
